import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import StarField from "@/components/StarField";
import CustomCursor from "@/components/CustomCursor";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hussam | AI / ML Developer",
  description: "Generated by Hussam Abdul Rahim",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // Add suppressHydrationWarning here
    <html lang="en" suppressHydrationWarning>
      <body className="bg-[#050505] text-white overflow-x-hidden">
        <StarField />
        <CustomCursor />
        <Navbar />
        {/* 'flex-grow' pushes the footer to the bottom if content is short */}
        <main className="flex-grow">
          {children}
          </main>
        <Footer />
      </body>
    </html>
  );
}
